services:
  postgres:
    image: postgres:15
    container_name: inventory-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nothing
      POSTGRES_DB: inventorydb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    container_name: inventory-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_KRAFT_MODE: "true"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    container_name: inventory-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  api:
    build:
      context: ../src/InventoryService.Api
      dockerfile: Dockerfile.Api
    depends_on:
      - postgres
      - kafka
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=inventorydb;Username=postgres;Password=postgres"
      Kafka__BootstrapServers: "kafka:9092"
    ports:
      - "5000:80"
